config/routes.rb
Rails.application.routes.draw do
  resources :locations
  root 'addresses#index'
  resources :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
require 'open_weather'


# get current weather by geocode. (lat, lon)
# OpenWeather::Current.geocode(9.94, 76.26)

# get the current weather in degrees celsius
# OpenWeather::Current.city("Cochin, IN", units: 'metric')
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:city, :zip)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :zip)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%#= f.label :zip %><br>
    <%#= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<% options = { units: "metric", APPID: "0adbf3f14350d0b4916e1e2bf59919f2" } %>
<%#= OpenWeather::Current.city("Berlin, DE", lang: "de") %>
<div class="weather-temperature">
  <%= @ip_client = request.remote_ip %>
  <%#= geocoded_by @ip_client %>
</div>

<p id="notice"><%= notice %></p>

<br><br>


<%#= wi_icon('day-lightning') %>

<%#= @temp.each do |temp| %> 
<%# end %>

<br>

<%#=  OpenWeather::Current.city_id("1273874") %>
<br>


<%#= OpenWeather::Current.geocode(26.9000, 75.80000) %>
<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th></th>
      <th>Weather Report</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
  
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.city %></td>
        <td><%#= address.zip %></td>
        <td><%#= link_to 'Show', address %>
         
         

          <%= @temp = OpenWeather::Current.city(address.city) %>

          <%if @temp["coord"].nil?%>
            <b>"Give Address is not Proper"</b>
          <%else%>
            <table border="2">
              <thead>
               <th>City</th>
               <th>Country</th>
               <th>Temp</th><!-- 
               <th>Min Temp </th>
               <th>Max Temp </th> -->
               <th>Humidity</th>
               <th>Sunrise</th>
               <th>Sunset</th>
              </thead>
              <tbody>
                <tr>
                  <td><%=@temp["name"] %></td>
                  <td><%=@temp["sys"]["country"] %></td>
                  <td><%= (@temp["main"]["temp"] - 273.15).round(2) %>°C</td><!-- 
                  <td><%#= (@temp["main"]["temp_min"] - 273.15).round(2) %> °C </td>
                  <td><%#= (@temp["main"]["temp_max"] - 273.15).round(2) %>°C </td> -->
                  <td><%= (@temp["main"]["humidity"]) %>%</td>
                  <td>
                    <% @sunrise_time = Time.at(@temp["sys"]["sunrise"]) %>

                    <%= @sunrise_time.hour %>:<%= @sunrise_time.min %>:<%= @sunrise_time.sec %>(<%= @sunrise_time.zone%>  
                  </td>
                  <td>
                    <% @sunset_time = Time.at(@temp["sys"]["sunset"]) %>
                    <%= @sunset_time.hour %>:<%= @sunset_time.min %>:<%= @sunset_time.sec %>(<%= @sunset_time.zone%>  
                  </td>

                  
                </tr>
              </tbody>
            </table>
          <%end%>

          <%#= @temp["coord"]["lon"] %>
          
        </td>
        <td><%#= link_to 'Edit', edit_address_path(address) %></td>
        <td><%#= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @address.zip %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherReport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.city %></td>
        <td><%= location.zip %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @location.zip %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>